# number of days to look back
num_days: 7

trim_len: 10000

docs:
  # - name: "Woo X"
  #   url: "https://docs.woox.io/#release-note"
  #   method: httpx
  # - name: "Binance"
  #   url: "https://binance-docs.github.io/apidocs/spot/en/#change-log"
  #   method: httpx
  - name: "Binance Spot Trading"
    url: "https://developers.binance.com/docs/binance-spot-api-docs/CHANGELOG"
    method: httpx
  # - name: "Binance Margin Trading"
  #   url: "https://developers.binance.com/docs/margin_trading/change-log"
  #   method: httpx
  # - name: "Binance Derivatives Trading"
  #   url: "https://developers.binance.com/docs/derivatives/change-log"
  #   method: httpx
  - name: "Coinbase Exchange"
    url: "https://docs.cdp.coinbase.com/exchange/docs/changelog/"
    method: playwright
  - name: "Coinbase Upcoming Changes"
    url: "https://docs.cdp.coinbase.com/exchange/docs/upcoming-changes"
    method: playwright
  - name: "MAX Exchange"
    url: "https://docs.google.com/document/d/1iLwjhU-AHSLB4UnZh3cPbkYL-M3-R0jW0MEL6iWt410/edit?tab=t.0#heading=h.z31cougdyqo7"
    method: playwright
  # - name: "Bybit Exchange"
  #   url: "https://bybit-exchange.github.io/docs/changelog/v5"
  #   method: httpx
  # - name: "Bitget Exchange"
  #   url: "https://www.bitget.com/api-doc/common/changelog"
  #   method: httpx
  - name: "OKX Exchange"
    url: https://www.okx.com/docs-v5/log_en/#upcoming-changes
    method: httpx
  # - name: "Huobi Exchange"
  #   url: "https://huobiapi.github.io/docs/spot/v1/en/#change-log"
  #   method: httpx
  # - name: "HitBTC Exchange"
  #   url: "https://api.hitbtc.com/#changelog"
  #   method: httpx

prompt: |
  從變更日誌或發行說明頁面中根據日期抽取前10筆變更或發行說明。
  如果標題 "Upcoming Changes" 存在，則抽取 upcoming changes 並總結其內容；否則，將輸出留空。

  指南:
  - 僅使用提供的上下文中的信息；避免使用佔位符或通用示例。
  - 將日期格式標準化並驗證為 'YYYY-MM-DD'（例如，將 '2024-Sep-20' 轉換為 '2024-09-20'）。
  - 如果某個日期沒有變更或發佈說明，則跳過該日期的提取。
  - 以 Markdown 格式呈現結果。
  - 真實示例應包含更精細的變更細節和多樣化的關鍵字。
  - 日期應該是實際的日期，而不是示例中的日期。

  步驟:
  - 提取所有按日期組織的條目，確保獲得前10筆記錄。
  - 如果日期尚未是 'YYYY-MM-DD' 格式，則進行轉換。
  - 對於每個條目，提取日期、變更摘要、關鍵字和類別。
  - 查詢標題為 "Upcoming Changes" 的部分，如果存在，提取摘要和類別；否則，將此部分的輸出設為空白。

  輸出值:
  針對相對應的 key，抽取對應的 value。
  - "date": 格式為 "YYYY-MM-DD" 的字符
  - "markdown_content": 以項目符號列表形式包含變更細節的字符串
  - "keywords": 與每個變更條目（不包括類別）相關的關鍵字數組
  - "categories": 指示與更新相關的類別的字符串數組（例如，BREAKING_CHANGES、NEW_FEATURES、BUG_FIXES、DEPRECATIONS、PERFORMANCE_IMPROVEMENTS、SECURITY_UPDATES）
