# number of days to look back
num_days: 14

trim_len: 10000

docs:
  - name: "Woo X"
    url: "https://docs.woox.io/#release-note"
  - name: "Binance"
    url: "https://binance-docs.github.io/apidocs/spot/en/#change-log"
  - name: "Binance Spot Trading"
    url: "https://developers.binance.com/docs/binance-spot-api-docs/CHANGELOG"
  - name: "Binance Margin Trading"
    url: "https://developers.binance.com/docs/margin_trading/change-log"
  - name: "Binance Derivatives Trading"
    url: "https://developers.binance.com/docs/derivatives/change-log"
  - name: "Bitfinex"
    url: "https://docs.bitfinex.com/docs/changelog"
  - name: "Kraken"
    url: "https://docs.kraken.com/api/docs/change-log"
  - name: "Coinbase Exchange"
    url: "https://docs.cdp.coinbase.com/exchange/docs/changelog/"
  - name: "Coinbase Upcoming Changes"
    url: "https://docs.cdp.coinbase.com/exchange/docs/upcoming-changes"
  - name: "MAX Exchange"
    url: "https://docs.google.com/document/d/1iLwjhU-AHSLB4UnZh3cPbkYL-M3-R0jW0MEL6iWt410/edit?tab=t.0#heading=h.z31cougdyqo7"
  - name: "Bybit Exchange"
    url: "https://bybit-exchange.github.io/docs/changelog/v5"
  - name: "Bitget Exchange"
    url: "https://www.bitget.com/api-doc/common/changelog"
  - name: "OKX Exchange"
    url: https://www.okx.com/docs-v5/log_en/#upcoming-changes
  - name: "Huobi Exchange"
    url: "https://huobiapi.github.io/docs/spot/v1/en/#change-log"
  - name: "HitBTC Exchange"
    url: "https://api.hitbtc.com/#changelog"

prompt: |
  You will be provided with content from an API documentation page in Markdown format. Your task is to extract and summarize up to 10 changes or release notes, prioritizing them by date as found in sections such as changelog or release notes. Additionally, extract and summarize upcoming changes only if the main heading "Upcoming Changes" is present; otherwise, leave the corresponding field blank.

  Please follow these instructions step by step for high-quality output:

  1. Identify and extract up to 10 distinct changes or release notes that are each associated with a specific date.
      - Only include entries with real, non-placeholder dates for which substantive information is provided.
      - Ignore entries that lack content, use placeholder dates, or serve as examples.
  2. Normalize all dates to the 'YYYY-MM-DD' format (e.g., convert '2024-Sep-20' to '2024-09-20'). Validate that each date is real and correctly formatted.
  3. For each extracted entry, summarize the change or release note in clear, plain text.
  4. Identify and list relevant keywords that summarize the main points (excluding generic category names).
  5. List the categories associated with each entry.
  6. If the "Upcoming Changes" main heading is present, extract and summarize the section beneath it. If not, leave the upcoming_changes field blank.
  7. Use only information directly provided in the content. Do not fabricate or add any placeholders.

  Output Format:
  For each extracted change, use the following structure:

  - date: The change or release date in 'YYYY-MM-DD' format.
  - items: A list of strings, each summarizing a change or release note in plain text.
  - keywords: An array of relevant keywords summarizing the main points of each entry, excluding category names.
  - categories: An array of strings representing the update categories.
  - upcoming_changes: A summary of the "Upcoming Changes" section if present; otherwise, leave this field blank.

  Think step by step to ensure that each instruction is carefully followed and that your output is accurate, complete, and adheres strictly to the provided context.
