# number of days to look back
num_days: 7

trim_len: 10000

docs:
  - name: "Woo X"
    url: "https://docs.woox.io/#release-note"
    method: httpx
  - name: "Binance"
    url: "https://binance-docs.github.io/apidocs/spot/en/#change-log"
    method: httpx
  - name: "Binance Spot Trading"
    url: "https://developers.binance.com/docs/binance-spot-api-docs/CHANGELOG"
    method: httpx
  - name: "Binance Margin Trading"
    url: "https://developers.binance.com/docs/margin_trading/change-log"
    method: httpx
  - name: "Binance Derivatives Trading"
    url: "https://developers.binance.com/docs/derivatives/change-log"
    method: httpx
  # - name: "Coinbase Exchange"
  #   url: "https://docs.cdp.coinbase.com/exchange/docs/changelog/"
  #   method: playwright
  # - name: "Coinbase Upcoming Changes"
  #   url: "https://docs.cdp.coinbase.com/exchange/docs/upcoming-changes"
  #   method: playwright
  # - name: "MAX Exchange"
  #   url: "https://docs.google.com/document/d/1iLwjhU-AHSLB4UnZh3cPbkYL-M3-R0jW0MEL6iWt410/edit?tab=t.0#heading=h.z31cougdyqo7"
  #   method: playwright
  - name: "Bybit Exchange"
    url: "https://bybit-exchange.github.io/docs/changelog/v5"
    method: httpx
  - name: "Bitget Exchange"
    url: "https://www.bitget.com/api-doc/common/changelog"
    method: httpx
  - name: "OKX Exchange"
    url: https://www.okx.com/docs-v5/log_en/#upcoming-changes
    method: httpx
  - name: "Huobi Exchange"
    url: "https://huobiapi.github.io/docs/spot/v1/en/#change-log"
    method: httpx
  - name: "HitBTC Exchange"
    url: "https://api.hitbtc.com/#changelog"
    method: httpx

prompt: |
  You are tasked with processing a changelog structured in a specific format. Your goal is to extract and organize changes and upcoming changes based on the provided classes.

  # Instructions:
  1. **Extract Changes**:
    - You will be provided with a list of `Change` objects, each containing:
      - `date`: The date of the change (ensure it is formatted as 'YYYY-MM-DD').
      - `markdown_content`: The content describing the change.
      - `keywords`: A list of keywords associated with the change.
      - `categories`: A list of categories from the `Category` enum.
    - Extract up to 10 changes, prioritizing them based on their `date`.

  2. **Extract Upcoming Changes**:
    - Access the `upcoming_changes` attribute from the `Changelog` object.
    - If this attribute contains content, summarize it. If it is empty, leave the output blank.

  # Output Format:
  - List the extracted changes in chronological order, including their dates and markdown content.
  - Provide a summary of the upcoming changes if applicable.

  # Note:
  - Ensure that all dates are real and formatted correctly. Do not include placeholders or fabricate information. Use only the data provided in the `Change` and `Changelog` classes.
