# number of days to look back
num_days: 7

trim_len: 10000

docs:
  - name: "Woo X"
    url: "https://docs.woox.io/#release-note"
    method: httpx
  - name: "Binance"
    url: "https://binance-docs.github.io/apidocs/spot/en/#change-log"
    method: httpx
  - name: "Binance Spot Trading"
    url: "https://developers.binance.com/docs/binance-spot-api-docs/CHANGELOG"
    method: httpx
  - name: "Binance Margin Trading"
    url: "https://developers.binance.com/docs/margin_trading/change-log"
    method: httpx
  - name: "Binance Derivatives Trading"
    url: "https://developers.binance.com/docs/derivatives/change-log"
    method: httpx
  - name: "Coinbase Exchange"
    url: "https://docs.cdp.coinbase.com/exchange/docs/changelog/"
    method: singlefile
  - name: "Coinbase Upcoming Changes"
    url: "https://docs.cdp.coinbase.com/exchange/docs/upcoming-changes"
    method: singlefile
  - name: "MAX Exchange"
    url: "https://docs.google.com/document/d/1iLwjhU-AHSLB4UnZh3cPbkYL-M3-R0jW0MEL6iWt410/edit?tab=t.0#heading=h.z31cougdyqo7"
    method: singlefile
  - name: "Bybit Exchange"
    url: "https://bybit-exchange.github.io/docs/changelog/v5"
    method: httpx
  - name: "Bitget Exchange"
    url: "https://www.bitget.com/api-doc/common/changelog"
    method: httpx
  - name: "OKX Exchange"
    url: https://www.okx.com/docs-v5/log_en/#upcoming-changes
    method: httpx
  - name: "Huobi Exchange"
    url: "https://huobiapi.github.io/docs/spot/v1/en/#change-log"
    method: httpx
  - name: "HitBTC Exchange"
    url: "https://api.hitbtc.com/#changelog"
    method: httpx

prompt: |
  You will be provided with content from an API documentation page in Markdown format.
  Extract and summarize up to 10 changes or release notes, prioritizing those based on their dates from the changelog or release notes section.
  Also, extract and summarize upcoming changes: if the main heading "Upcoming Changes" is present, extract and summarize the content beneath it; if not, leave the output blank.

  Instructions:
  - Date Validation: Ensure all dates are in the format 'YYYY-MM-DD' (e.g., convert '2024-Sep-20' to '2024-09-20'). Dates must be real and not placeholders.
  - Extraction Rules:
  - Only extract dates that have actual changes or release notes associated with them.
  - Skip entries without substantive information or dates that serve as examples or placeholders.
  - Content Integrity: Use only the information directly provided in the context—do not fabricate or include placeholders.

  Output Format:
  For each extracted entry, provide the following:
  - date: The release or change date.
  - markdown_content: The content of the change or release note in bullet-point Markdown format.
  - keywords: An array of relevant keywords summarizing the main points of each entry (excluding category names).
  - categories: An array of strings representing the categories related to the update.
  - upcoming_changes: A summary of the "Upcoming Changes" section, if present. Otherwise, this field should be left blank.
