name: Cron

on:
  workflow_dispatch:
  # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
  schedule:
    - cron: "0 0 * * 1,4"
  # push:
  #   branches:
  #     - main

jobs:
  cron:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: |
          uv sync
          uv run playwright install
          uv run python main.py -c config/default.yaml -o changelog.md
        env:
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          OPENAI_API_VERSION: ${{ vars.OPENAI_API_VERSION }}
          SINGLEFILE_PATH: ${{ secrets.SINGLEFILE_PATH }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL }}
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
          LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
          LANGFUSE_HOST: ${{ vars.LANGFUSE_HOST }}
          LOGFIRE_ENVIRONMENT: prod
          REDIS_URL: ${{ secrets.REDIS_URL }}
      - uses: danielmcconville/gist-sync-file-action@v2.0.0
        with:
          gistPat: ${{ secrets.GIST_TOKEN }}
          action: update
          filename: changelog.md
          gistId: ${{ secrets.GIST_ID }}
          createIfNotExists: true
