name: Cron Dev

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 */7 * *"

jobs:
  cron:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: |
          poetry install
          poetry run python main.py -c config/default.yaml -o changelog-dev.md
        env:
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SINGLEFILE_PATH: ${{ secrets.SINGLEFILE_PATH }}
      - uses: danielmcconville/gist-sync-file-action@v2.0.0
        with:
          gistPat: ${{ secrets.GIST_TOKEN }}
          action: update
          filename: changelog-dev.md
          gistId: ${{ secrets.GIST_ID }}
          createIfNotExists: true
