name: Docker Cron

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 */7 * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    container:
      image: narumi/exchange-changelog:main
      env:
        OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL }}
        LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
        LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
        LANGFUSE_HOST: ${{ vars.LANGFUSE_HOST }}
        REDIS_URL: ${{ secrets.REDIS_URL }}
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - run: |
          cp /.dockerenv /app/.env
          exchange-changelog
        working-directory: /app
