name: Dev

on:
  workflow_dispatch:
    inputs:
      config_file:
        description: "Config file"
        required: true
        default: "config/dev.yaml"

jobs:
  dev:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: |
          uv sync
          uv run playwright install
          uv run exchange-changelog -c ${{ inputs.config_file }} -o changelog.md
        env:
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          OPENAI_API_VERSION: ${{ vars.OPENAI_API_VERSION }}
          SINGLEFILE_PATH: ${{ secrets.SINGLEFILE_PATH }}
          SLACK_TOKEN: ${{ secrets.DEV_SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ vars.DEV_SLACK_CHANNEL }}
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
          LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
          LANGFUSE_HOST: ${{ vars.LANGFUSE_HOST }}
          LOGFIRE_ENVIRONMENT: dev
          # REDIS_URL: ${{ secrets.REDIS_URL }}
      - uses: danielmcconville/gist-sync-file-action@v2.0.0
        with:
          gistPat: ${{ secrets.GIST_TOKEN }}
          action: update
          filename: changelog.md
          gistId: ${{ secrets.DEV_GIST_ID }}
          createIfNotExists: true
