name: Dev

on:
  workflow_dispatch:
    inputs:
      config_file:
        description: "Config file"
        required: true
        default: "config/dev.yaml"

jobs:
  dev:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: |
          uv sync
          uv run playwright install
          uv run python main.py -c ${{ inputs.config_file }} -o changelog.md
        env:
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SINGLEFILE_PATH: ${{ secrets.SINGLEFILE_PATH }}
      - uses: danielmcconville/gist-sync-file-action@v2.0.0
        with:
          gistPat: ${{ secrets.GIST_TOKEN }}
          action: update
          filename: changelog.md
          gistId: ${{ secrets.DEV_GIST_ID }}
          createIfNotExists: true
